# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: '4b62f712-a05d-4004-916b-73432999b6ac' 
  staticWebAppName: 'apicurrencyconverterfrontend'      
  appArtifactLocation: 'build'  
  playwrightTestLocation: 'frontend/tests'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npx playwright install  # Installs the necessary browser binaries for Playwright
    npx playwright test $(playwrightTestLocation)  # Run Playwright tests
  displayName: 'Run Playwright tests'

- script: |
    npm run build
  displayName: 'npm run build'

- task: AzureStaticWebApp@0
  inputs:
    azureSubscription: '4b62f712-a05d-4004-916b-73432999b6ac'
    app_location: '/'
    api_location: ''
    app_artifact_location: $(Build.ArtifactStagingDirectory)/$(appArtifactLocation)
    deployment_token: $(deployment_token)  # You can get this token from the Azure portal