# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - azure-pipelines
  paths:
    include:
    - backend/*

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'd5f7e6ad-beca-45ba-9be5-bc1825fb9b5a'

  # Web app name
  webAppName: 'apicurrencyconverterbackend'

  # Environment name
  environmentName: 'apicurrencyconverterbackend'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'backend/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17' 
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: 'backend**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: Maven@4
      displayName: 'Maven - Generate Coverage Report'
      inputs:
        mavenPomFile: 'backend/pom.xml'
        goals: 'clean verify'
        options: '-DskipTests=false'
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Code Coverage Results'
      inputs:
        summaryFileLocation: 'backend/target/site/jacoco/jacoco.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/backend'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: apicurrencyconverterbackend'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
